package ru.job4j.basic.sync.sharedresources.cash;

/**
 * Данный класс (точнее запись) описывает
 * аккаунт пользователя.
 * Для формирования модели данных,
 * мы использовали record.
 *
 * Records are immutable data
 * classes that require only
 * the type and name of fields.
 * The equals, hashCode, and
 * toString methods, as well as
 * the private, final fields and
 * public constructor, are
 * generated by the Java compiler.
 *
 * @param id идентификатор.
 * @param amount баланс.
 */
public record Account(int id, int amount) {
}
